### PR TITLE
Added CRF layer, a smoothness metric and heuristic smoothing algorithm

### PR DESCRIPTION
**Pull request by timkartar**
Option to log a a list of scalar parameters and their gradients. Added as an optional input to Trainer.train(). The list should contain names of params or partial name.

Example usage:
```
params_to_log = []
for name, param in model.named_parameters():
    if "log" in name:
        params_to_log.append(name)

trainer.train(C["epochs"], DL_tr, DL_vl, checkpoint_every=ARGS.checkpoint_every, params_to_write=params_to_log)
```

### CODE REVIEW

**Review by jaredsagendorf — COMMENTED** [review]
Does this work if the parameter is not a scalar? I know you were using it to log alpha/beta but will this fail for a higher dimensional tensor?

**Comment by timkartar** [comment]
Yes, I think it will not work for non-scalars, I could not find a straightforward way to log vectors at that point of time. I found examples for visualizing images and histograms (https://gist.github.com/gyglim/1f8dfb1b5c82627ae3efcfbbadb9f514), but not of vectors. For logging vectors, it's probably easier to just save them in npy files (assuming they have high dimensions and cannot be plotted).

**Comment by jaredsagendorf** [comment]
> Yes, I think it will not work for non-scalars, I could not find a straightforward way to log vectors at that point of time. I found examples for visualizing images and histograms (https://gist.github.com/gyglim/1f8dfb1b5c82627ae3efcfbbadb9f514), but not of vectors. For logging vectors, it's probably easier to just save them in npy files (assuming they have high dimensions and cannot be plotted).

Plotting histograms v.s. time is probably the best way to handle it, which fortunately tensorboard can do. Could you include the cases where someone might want to look how some non-scalar model parameters are changing over time?

Let's say if the parameter is a 2x2 matrix or less, then each component will be plotted as a scalar. For example, if  is a parameter then automatically we'd plot a_11, a_12, a_21, a_22 v.s. time on four different plots. But  would get plotted as a histogram v.s. time.

Does that sound reasonable?

**Comment by timkartar** [comment]
I see. Yes, it does. I will first do the other main codes and then come back and do this.

**Comment by timkartar** [comment]
Hi Jared,

In the commit above, I have added the code for crf layer, smoothness metrics, heuristic smoothing. I could not make a separate request unless this one is pulled. I may not be able to get into the logging tensor part soon due to other end of term heavy works coming up. So, I request you to pull this request. I will make another one titled 'logging tensor parameters ...' later when I can get into that. 

Also, something you changed in geobind since I installed it regarding how data is loaded makes the old train_model script you gave broken. Probably having an 'example' directory with an example of the same (and other stuff you feel like) will be nice!

**Comment by jaredsagendorf** [comment]
Thanks Raktim, a few notes:

1. You can submit multiple pull requests, they just need to be on different branches. A PR is for an entire branch.
2. Your PR was originally about logging model parameters with Tensorboard (and that feature is not even fully implemented in this PR). It now contains a bunch of other commits that have nothing to do with the original feature mentioned in the PR, and should definitely have been a separate PR. This is bad practice because now any future developer looking back on this is going to be very confused about what exactly was done in this PR on your part... I have modified the title to help clarify a little bit.
3. When you write comments please don't use that indentation style where the comments are far off to the right side. Just keep it simple - if it's a comment that requires more than a few words or refers to several lines of code, put it above the block of code. If it refers to only a single line and is very short, put it at the end of the line

**Comment by timkartar** [comment]
Hi Jared, thanks, I shall keep those in mind in future, however, my original pull request had specifically said "scalar", so I do not think it was not implemented. I am adding "logging scalar parameters to the title again". I shall create one for tensor when I get it done. Thanks.

**Pull request merged**
