### PR TITLE
Logging Tensor parameters and added missing argument in train()

### PR DESCRIPTION
**Pull request by timkartar**
Added code for logging tensor parameters to tensorboard as discussed in #1  and added missing argument in train() method.

### CODE REVIEW

**Comment by jaredsagendorf** [comment]
Can you fix the conflicts? Also look at how I simplified your loop... the current version is quite messy. When you title a PR, you don't need to say something like "added missing argument in train()" - little details like that should be documented in the commit history

**Comment by timkartar** [comment]
Hi Jared, I was allowing for partial names of parameters to be given, i.e.`param` may not be in `params_to_write` but a partial part of it could be. If you think that's not needed, then your loop is fine. Thanks.

**Comment by jaredsagendorf** [comment]
I see... that is not a bad idea, but I think the main use of this feature will be for debugging purposes, and in that case it's probably best to require exact names to be provided so that there is no possible mix-up of variables with similar names.

**Comment by timkartar** [comment]
I fixed the conflict. But do not pull it right now, I still cannot run geobind (so not tested in geobind framework), something regarding data loading is not working. Maybe I can show you what's happening when we meet.

**Comment by timkartar** [comment]
Ok, this is tested inside geobind, working nicely and ready to be pulled 👍

**Pull request merged**
